AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Environment:
    Description: Defines environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - beta
      - prod
    ConstraintDescription: Use valid environment [dev, qa, beta, prod]

  NumberOfInstances:
    Description: Number of instances to launch
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 5
    ConstraintDescription: Must be between 1 and 5

Rules:
  ProdDevEnvironmentRule:
    Assertions:
      - Assert: !Equals [ !Ref NumberOfInstances, "5" ]
        AssertDescription: Prod y Dev deben tener 5 instancias
    RuleCondition:
      Fn::Or:
        - Fn::Equals:
            - !Ref Environment
            - prod
        - Fn::Equals:
            - !Ref Environment
            - dev
   

Resources:
  DemoBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: NumberOfInstances
          Value: !Ref NumberOfInstances